/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLLThanhVien;
import javax.swing.JOptionPane;

/**
 *
 * @author tuvu
 */
public class InsertMemberDlg extends javax.swing.JDialog {
    private BLLThanhVien thanhVienBLL;
    /**
     * Creates new form InsertMemberDlg
     */
    public InsertMemberDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        thanhVienBLL = new BLLThanhVien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        insert_tv_label = new javax.swing.JLabel();
        hovatentv_label = new javax.swing.JLabel();
        khoatv_label = new javax.swing.JLabel();
        nganhtv_label = new javax.swing.JLabel();
        sdttv_label = new javax.swing.JLabel();
        passwordtv_label = new javax.swing.JLabel();
        emailtv_label = new javax.swing.JLabel();
        hovaten_textfield = new javax.swing.JTextField();
        khoa_textfield = new javax.swing.JTextField();
        nganh_textfield = new javax.swing.JTextField();
        sdt_textfield = new javax.swing.JTextField();
        password_textfield = new javax.swing.JTextField();
        email_textfield = new javax.swing.JTextField();
        addtv_label = new javax.swing.JButton();
        masv_label = new javax.swing.JLabel();
        masv_textfield = new javax.swing.JTextField();

        jTextField4.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        insert_tv_label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        insert_tv_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        insert_tv_label.setText("THÊM MỚI THÀNH VIÊN");

        hovatentv_label.setText("Họ và tên:");

        khoatv_label.setText("Khoa:");

        nganhtv_label.setText("Ngành:");

        sdttv_label.setText("Sdt:");

        passwordtv_label.setText("Password:");

        emailtv_label.setText("Email:");

        email_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_textfieldActionPerformed(evt);
            }
        });

        addtv_label.setText("Thêm");
        addtv_label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtv_labelActionPerformed(evt);
            }
        });

        masv_label.setText("Mã sinh viên:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(addtv_label, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(masv_label)
                    .addComponent(emailtv_label)
                    .addComponent(hovatentv_label)
                    .addComponent(khoatv_label)
                    .addComponent(nganhtv_label)
                    .addComponent(sdttv_label)
                    .addComponent(passwordtv_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(insert_tv_label, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hovaten_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(khoa_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(nganh_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(sdt_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(password_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(email_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(masv_textfield))
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(insert_tv_label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(masv_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 23, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(masv_textfield)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hovatentv_label)
                    .addComponent(hovaten_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(khoatv_label)
                    .addComponent(khoa_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nganhtv_label)
                    .addComponent(nganh_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sdttv_label)
                    .addComponent(sdt_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordtv_label)
                    .addComponent(password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailtv_label)
                    .addComponent(email_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addtv_label, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addtv_labelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtv_labelActionPerformed
        addMember();
    }//GEN-LAST:event_addtv_labelActionPerformed

    private void email_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_textfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertMemberDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertMemberDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertMemberDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertMemberDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InsertMemberDlg dialog = new InsertMemberDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addtv_label;
    private javax.swing.JTextField email_textfield;
    private javax.swing.JLabel emailtv_label;
    private javax.swing.JTextField hovaten_textfield;
    private javax.swing.JLabel hovatentv_label;
    private javax.swing.JLabel insert_tv_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField khoa_textfield;
    private javax.swing.JLabel khoatv_label;
    private javax.swing.JLabel masv_label;
    private javax.swing.JTextField masv_textfield;
    private javax.swing.JTextField nganh_textfield;
    private javax.swing.JLabel nganhtv_label;
    private javax.swing.JTextField password_textfield;
    private javax.swing.JLabel passwordtv_label;
    private javax.swing.JTextField sdt_textfield;
    private javax.swing.JLabel sdttv_label;
    // End of variables declaration//GEN-END:variables

    private void addMember() {
        String stringMaTV = masv_textfield.getText();
        String hoVaTen = hovaten_textfield.getText();
        String khoa = khoa_textfield.getText();
        String nganh = nganh_textfield.getText();
        String sdt = sdt_textfield.getText();
        String password = password_textfield.getText();
        String email = email_textfield.getText();

        // Kiểm tra xem các trường nhập liệu có trống không
        if (stringMaTV.isEmpty() || hoVaTen.isEmpty() || khoa.isEmpty() || nganh.isEmpty() ||
                sdt.isEmpty() || password.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Không thêm thành viên nếu có trường nhập liệu trống
        }

        if (stringMaTV.length() != 10) {
            JOptionPane.showMessageDialog(this, "Mã sinh viên phải có đúng 10 ký tự.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Không thêm thành viên nếu mã sinh viên không đủ 10 ký tự
        }

        int sdtValue = 0;
        try {
            sdtValue = Integer.parseInt(sdt);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ: " + sdt, "Error", JOptionPane.ERROR_MESSAGE);
            return; // Không thêm thành viên nếu số điện thoại không hợp lệ
        }

        // Kiểm tra định dạng email
        if (!email.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")) {
            JOptionPane.showMessageDialog(this, "Định dạng email không hợp lệ.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Không thêm thành viên nếu định dạng email không hợp lệ
        }

        int MaTV = 0;
        try {
            MaTV = Integer.parseInt(stringMaTV);
            System.out.println("Integer value: " + MaTV);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Số thẻ thành viên không hợp lệ: " + stringMaTV, "Error", JOptionPane.ERROR_MESSAGE);
            return; // Không thêm thành viên nếu số thẻ không hợp lệ
        }

        // Thêm thành viên vào cơ sở dữ liệu
        if (thanhVienBLL.insertThanhVien(MaTV, hoVaTen, khoa, nganh, sdt, password, email)) {
            JOptionPane.showMessageDialog(this, "Thêm mới thành viên thành công", "Success", JOptionPane.INFORMATION_MESSAGE);
            setVisible(false);
            PanelMember pn = new PanelMember();
            pn.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

}
