/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author tuvu
 */
public class UpdateMemberDlg extends javax.swing.JDialog {
    private BLL.BLLThanhVien thanhVienBLL;
    private int maTV;
    private String hoTen;
    private String khoa;
    private String nganh;
    private String sdt;
    private String password;
    private String email;
    /**
     * Creates new form UpdateMemberDlg
     */
    public UpdateMemberDlg(java.awt.Frame parent, boolean modal, int maTV, String hoTen, String khoa, String nganh, String sdt, String password, String email) {
        super(parent, modal);
        thanhVienBLL = new BLL.BLLThanhVien();
        initComponents();
        this.maTV = maTV;
        this.hoTen = hoTen;
        this.khoa = khoa;
        this.nganh = nganh;
        this.sdt = sdt;
        this.password = password;
        this.email = email;
        loadData(maTV, hoTen, khoa, nganh, sdt, password, email);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        update_tv_label = new javax.swing.JLabel();
        hovatentv_label = new javax.swing.JLabel();
        khoatv_label = new javax.swing.JLabel();
        nganhtv_label = new javax.swing.JLabel();
        sdttv_label = new javax.swing.JLabel();
        passwordtv_label = new javax.swing.JLabel();
        emailtv_label = new javax.swing.JLabel();
        hovaten_textfield = new javax.swing.JTextField();
        khoa_textfield = new javax.swing.JTextField();
        nganh_textfield = new javax.swing.JTextField();
        sdt_textfield = new javax.swing.JTextField();
        password_textfield = new javax.swing.JTextField();
        email_textfield = new javax.swing.JTextField();
        updatetv_label = new javax.swing.JButton();
        masv_label = new javax.swing.JLabel();
        masv_textfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        update_tv_label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        update_tv_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        update_tv_label.setText("Cập Nhật Thành Viên");

        hovatentv_label.setText("Họ và tên:");

        khoatv_label.setText("Khoa:");

        nganhtv_label.setText("Ngành:");

        sdttv_label.setText("Sdt:");

        passwordtv_label.setText("Password:");

        emailtv_label.setText("Email:");

        email_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_textfieldActionPerformed(evt);
            }
        });

        updatetv_label.setText("Cập Nhật");
        updatetv_label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatetv_labelActionPerformed(evt);
            }
        });

        masv_label.setText("Mã thành viên:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(updatetv_label, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(masv_label)
                    .addComponent(emailtv_label)
                    .addComponent(hovatentv_label)
                    .addComponent(khoatv_label)
                    .addComponent(nganhtv_label)
                    .addComponent(sdttv_label)
                    .addComponent(passwordtv_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(update_tv_label, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hovaten_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(khoa_textfield)
                    .addComponent(nganh_textfield)
                    .addComponent(sdt_textfield)
                    .addComponent(password_textfield)
                    .addComponent(email_textfield)
                    .addComponent(masv_textfield))
                .addGap(96, 96, 96))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(update_tv_label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(masv_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 20, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(masv_textfield)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hovatentv_label)
                    .addComponent(hovaten_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(khoatv_label)
                    .addComponent(khoa_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nganhtv_label)
                    .addComponent(nganh_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sdttv_label)
                    .addComponent(sdt_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordtv_label)
                    .addComponent(password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailtv_label)
                    .addComponent(email_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updatetv_label, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void email_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_textfieldActionPerformed

    private void updatetv_labelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatetv_labelActionPerformed
        UpdateMember();
    }//GEN-LAST:event_updatetv_labelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMemberDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMemberDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMemberDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMemberDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateMemberDlg dialog = new UpdateMemberDlg(new javax.swing.JFrame(), true, 0, "", "", "", "", "", "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email_textfield;
    private javax.swing.JLabel emailtv_label;
    private javax.swing.JTextField hovaten_textfield;
    private javax.swing.JLabel hovatentv_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField khoa_textfield;
    private javax.swing.JLabel khoatv_label;
    private javax.swing.JLabel masv_label;
    private javax.swing.JTextField masv_textfield;
    private javax.swing.JTextField nganh_textfield;
    private javax.swing.JLabel nganhtv_label;
    private javax.swing.JTextField password_textfield;
    private javax.swing.JLabel passwordtv_label;
    private javax.swing.JTextField sdt_textfield;
    private javax.swing.JLabel sdttv_label;
    private javax.swing.JLabel update_tv_label;
    private javax.swing.JButton updatetv_label;
    // End of variables declaration//GEN-END:variables

    private void UpdateMember() {
        String stringMaTV = masv_textfield.getText();
        String hoVaTen = hovaten_textfield.getText();
        String khoa = khoa_textfield.getText();
        String nganh = nganh_textfield.getText();
        String sdt = sdt_textfield.getText();
        String password = password_textfield.getText();
        String email = email_textfield.getText();

        // Kiểm tra xem các trường nhập liệu có trống không
        if (stringMaTV.isEmpty() || hoVaTen.isEmpty() || khoa.isEmpty() || nganh.isEmpty() ||
                sdt.isEmpty() || password.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Không thêm thành viên nếu có trường nhập liệu trống
        }

        if (stringMaTV.length() != 10) {
            JOptionPane.showMessageDialog(this, "Mã sinh viên phải có đúng 10 ký tự.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Không thêm thành viên nếu mã sinh viên không đủ 10 ký tự
        }

        int sdtValue = 0;
        try {
            sdtValue = Integer.parseInt(sdt);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ: " + sdt, "Error", JOptionPane.ERROR_MESSAGE);
            return; // Không thêm thành viên nếu số điện thoại không hợp lệ
        }

        // Kiểm tra định dạng email
        if (!email.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")) {
            JOptionPane.showMessageDialog(this, "Định dạng email không hợp lệ.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Không thêm thành viên nếu định dạng email không hợp lệ
        }

        int MaTV = 0;
        try {
            MaTV = Integer.parseInt(stringMaTV);
            System.out.println("Integer value: " + MaTV);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Số thẻ thành viên không hợp lệ: " + stringMaTV, "Error", JOptionPane.ERROR_MESSAGE);
            return; // Không thêm thành viên nếu số thẻ không hợp lệ
        }

        // Thêm thành viên vào cơ sở dữ liệu
        if (thanhVienBLL.updateThanhVien(MaTV, hoVaTen, khoa, nganh, sdt, password, email)) {
            JOptionPane.showMessageDialog(this, "Cập nhật thành viên thành công", "Success", JOptionPane.INFORMATION_MESSAGE);
            setVisible(false);
            PanelMember pn = new PanelMember();
            pn.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadData(int maTV, String hoTen, String khoa, String nganh, String sdt, String password, String email) {
        String MaTV = Integer.toString(maTV);
        masv_textfield.setText(MaTV);
        hovaten_textfield.setText(hoTen);
        masv_textfield.setEnabled(false);
        khoa_textfield.setText(khoa);
        nganh_textfield.setText(nganh);
        sdt_textfield.setText(sdt);
        password_textfield.setText(password);
        email_textfield.setText(email);
    }
}
